//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPC2Proyecto.ReferenciaWeb {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WS/", ConfigurationName="ReferenciaWeb.WsUsuario")]
    public interface WsUsuario {
        
        // CODEGEN: Generating message contract since element name nombre from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/WsUsuario/AgregarUsuarioRequest", ReplyAction="http://WS/WsUsuario/AgregarUsuarioResponse")]
        IPC2Proyecto.ReferenciaWeb.AgregarUsuarioResponse AgregarUsuario(IPC2Proyecto.ReferenciaWeb.AgregarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/WsUsuario/AgregarUsuarioRequest", ReplyAction="http://WS/WsUsuario/AgregarUsuarioResponse")]
        System.Threading.Tasks.Task<IPC2Proyecto.ReferenciaWeb.AgregarUsuarioResponse> AgregarUsuarioAsync(IPC2Proyecto.ReferenciaWeb.AgregarUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/WsUsuario/helloRequest", ReplyAction="http://WS/WsUsuario/helloResponse")]
        IPC2Proyecto.ReferenciaWeb.helloResponse hello(IPC2Proyecto.ReferenciaWeb.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/WsUsuario/helloRequest", ReplyAction="http://WS/WsUsuario/helloResponse")]
        System.Threading.Tasks.Task<IPC2Proyecto.ReferenciaWeb.helloResponse> helloAsync(IPC2Proyecto.ReferenciaWeb.helloRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarUsuario", Namespace="http://WS/", Order=0)]
        public IPC2Proyecto.ReferenciaWeb.AgregarUsuarioRequestBody Body;
        
        public AgregarUsuarioRequest() {
        }
        
        public AgregarUsuarioRequest(IPC2Proyecto.ReferenciaWeb.AgregarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class AgregarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string correo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fecha_nac;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string nick;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string contrasena;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string karma;
        
        public AgregarUsuarioRequestBody() {
        }
        
        public AgregarUsuarioRequestBody(string nombre, string correo, string fecha_nac, string nick, string contrasena, string karma) {
            this.nombre = nombre;
            this.correo = correo;
            this.fecha_nac = fecha_nac;
            this.nick = nick;
            this.contrasena = contrasena;
            this.karma = karma;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarUsuarioResponse", Namespace="http://WS/", Order=0)]
        public IPC2Proyecto.ReferenciaWeb.AgregarUsuarioResponseBody Body;
        
        public AgregarUsuarioResponse() {
        }
        
        public AgregarUsuarioResponse(IPC2Proyecto.ReferenciaWeb.AgregarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class AgregarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public AgregarUsuarioResponseBody() {
        }
        
        public AgregarUsuarioResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hello", Namespace="http://WS/", Order=0)]
        public IPC2Proyecto.ReferenciaWeb.helloRequestBody Body;
        
        public helloRequest() {
        }
        
        public helloRequest(IPC2Proyecto.ReferenciaWeb.helloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public helloRequestBody() {
        }
        
        public helloRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="helloResponse", Namespace="http://WS/", Order=0)]
        public IPC2Proyecto.ReferenciaWeb.helloResponseBody Body;
        
        public helloResponse() {
        }
        
        public helloResponse(IPC2Proyecto.ReferenciaWeb.helloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public helloResponseBody() {
        }
        
        public helloResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsUsuarioChannel : IPC2Proyecto.ReferenciaWeb.WsUsuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsUsuarioClient : System.ServiceModel.ClientBase<IPC2Proyecto.ReferenciaWeb.WsUsuario>, IPC2Proyecto.ReferenciaWeb.WsUsuario {
        
        public WsUsuarioClient() {
        }
        
        public WsUsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsUsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsUsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsUsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IPC2Proyecto.ReferenciaWeb.AgregarUsuarioResponse IPC2Proyecto.ReferenciaWeb.WsUsuario.AgregarUsuario(IPC2Proyecto.ReferenciaWeb.AgregarUsuarioRequest request) {
            return base.Channel.AgregarUsuario(request);
        }
        
        public string AgregarUsuario(string nombre, string correo, string fecha_nac, string nick, string contrasena, string karma) {
            IPC2Proyecto.ReferenciaWeb.AgregarUsuarioRequest inValue = new IPC2Proyecto.ReferenciaWeb.AgregarUsuarioRequest();
            inValue.Body = new IPC2Proyecto.ReferenciaWeb.AgregarUsuarioRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.correo = correo;
            inValue.Body.fecha_nac = fecha_nac;
            inValue.Body.nick = nick;
            inValue.Body.contrasena = contrasena;
            inValue.Body.karma = karma;
            IPC2Proyecto.ReferenciaWeb.AgregarUsuarioResponse retVal = ((IPC2Proyecto.ReferenciaWeb.WsUsuario)(this)).AgregarUsuario(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IPC2Proyecto.ReferenciaWeb.AgregarUsuarioResponse> IPC2Proyecto.ReferenciaWeb.WsUsuario.AgregarUsuarioAsync(IPC2Proyecto.ReferenciaWeb.AgregarUsuarioRequest request) {
            return base.Channel.AgregarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<IPC2Proyecto.ReferenciaWeb.AgregarUsuarioResponse> AgregarUsuarioAsync(string nombre, string correo, string fecha_nac, string nick, string contrasena, string karma) {
            IPC2Proyecto.ReferenciaWeb.AgregarUsuarioRequest inValue = new IPC2Proyecto.ReferenciaWeb.AgregarUsuarioRequest();
            inValue.Body = new IPC2Proyecto.ReferenciaWeb.AgregarUsuarioRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.correo = correo;
            inValue.Body.fecha_nac = fecha_nac;
            inValue.Body.nick = nick;
            inValue.Body.contrasena = contrasena;
            inValue.Body.karma = karma;
            return ((IPC2Proyecto.ReferenciaWeb.WsUsuario)(this)).AgregarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IPC2Proyecto.ReferenciaWeb.helloResponse IPC2Proyecto.ReferenciaWeb.WsUsuario.hello(IPC2Proyecto.ReferenciaWeb.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            IPC2Proyecto.ReferenciaWeb.helloRequest inValue = new IPC2Proyecto.ReferenciaWeb.helloRequest();
            inValue.Body = new IPC2Proyecto.ReferenciaWeb.helloRequestBody();
            inValue.Body.name = name;
            IPC2Proyecto.ReferenciaWeb.helloResponse retVal = ((IPC2Proyecto.ReferenciaWeb.WsUsuario)(this)).hello(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IPC2Proyecto.ReferenciaWeb.helloResponse> IPC2Proyecto.ReferenciaWeb.WsUsuario.helloAsync(IPC2Proyecto.ReferenciaWeb.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<IPC2Proyecto.ReferenciaWeb.helloResponse> helloAsync(string name) {
            IPC2Proyecto.ReferenciaWeb.helloRequest inValue = new IPC2Proyecto.ReferenciaWeb.helloRequest();
            inValue.Body = new IPC2Proyecto.ReferenciaWeb.helloRequestBody();
            inValue.Body.name = name;
            return ((IPC2Proyecto.ReferenciaWeb.WsUsuario)(this)).helloAsync(inValue);
        }
    }
}
